---
title: "Exercise"
author: "Erik"
date: "1/27/2020"
output: html_document
---
```{r}


```

```{r}
install.packages(forecast)
```

```{r}
library(forecast)
acf(wineind,lag.max = 100)
```

```{r}

len = 1993-1980+1
data0 = wineind[1:12*len]
range0 = range(data0) + c(-100,100)
plot(1:12, 1:12, ylim=range0, col= 'white', xlab="month", ylab="sales")
for (i in 1:len)
{
  points(1:12, wineind[12*(i-1)+1:(12*i)])
  lines(1:12, wineind[12*(i-1)+1:(12*i)], lty = 2)
}
```

```{r}
Month = NULL
DstValue = NULL
RecentVal1 = NULL
RecentVal4 = NULL
RecentVal6 = NULL
RecentVal8 = NULL
RecentVal12 = NULL

wineind[wineind<18000] = 18000
wineind[wineind>38000] = 38000
for (i in (12+1):(length(wineind-1)))
{
  Month <- c(Month, i%%12+1)
  DstValue  <- c(DstValue, wineind[i+1])
  RecentVal1 <- c(RecentVal1, wineind[i])
  RecentVal4 <- c(RecentVal4, wineind[i-3])
  RecentVal6 <- c(RecentVal6, wineind[i-5])
  RecentVal8 <- c(RecentVal8, wineind[i-7])
  RecentVal12 <- c(RecentVal12, wineind[i-11])
}
preData = data.frame(Month, DstValue, RecentVal1, RecentVal4, RecentVal6, RecentVal8, RecentVal12)
head(preData)
plot(preData)
```
```{r}
lm.fit = lm(DstValue~RecentVal12, data=preData)
cook<-cooks.distance(lm.fit)
plot(cook)
abline(h=0.15, lty=2, col='red')
```
```{r}
cook[cook>0.15]
preData=preData[-c(123,79),]
```
```{r}
trainData = preData[1:150,]
testData = preData[151:163,]

lm.fit<-lm(DstValue~Month + RecentVal1 + RecentVal4 + RecentVal6 + RecentVal8 + RecentVal12, data=trainData)
summary(lm.fit)
```
```{r}

```





```{r}

```
